version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  api:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: bash -c "npm run test && npm run seed && npm run start"
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:
